# specifiy docker version
version: "3"
# define list of containers 
services:
  # web app
  web:
    # name of container
    container_name: itstimeapi
    # define service will be built with dockerfile
    build: .
    # restart on reboot
    restart: always
    # define file containing secrets
    env_file:
      - .env
    # specify container should start after mysql service is up
    depends_on:
      - mysql
  # define mysql
  mysql:
    # name of container
    container_name: mysql
    # lower resource usage than mysql
    image: mariadb
    # restart on reboot
    restart: always
    # define secrets file
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
  # define nginx container 
  nginx:
    # define container name
    container_name: nginx
    # which image to use
    image: jonasal/nginx-certbot
    # restart on reboot
    restart: always
    # generates certificates
    environment:
      - CERTBOT_EMAIL=gino.rey@outlook.com
    # bind ports to the internet
    ports:
      - 80:80
      - 443:443
    # store certificate files in a volume
    volumes:
      - nginx_secrets:/etc/letsencrypt
      # map config files into the container
      - ./user_conf.d:/etc/nginx/user_conf.d
    # boot after web app
    depends_on:
      - web

# define volumes that will persist if container reboot
volumes:
  mydatabase:
  nginx_secrets:
