version: "3"
services:
  itstimeapi:
    container_name: itstimeapi
    build: .
    restart: always
    env_file:
      - .env
    enviornment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/itstimeapi
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
  
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    # generates certificates
    environment:
      - CERTBOT_EMAIL=gino.rey@outlook.com
    # bind ports to the internet
    ports:
      - 80:80
      - 443:443
    # store certificate files in a volume
    volumes:
      - nginx_secrets:/etc/letsencrypt
      # map config files into the container
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - itstimeapi

volumes:
  mydatabase:
  nginx_secrets:
